### PR TITLE
Dev valeryvs clean

### PR DESCRIPTION
**Pull request by ValeryVS**
All my updates in one branch to prevent merge conflicts.
I will update this when there will be new updates.

### CODE REVIEW

**Comment by ValeryVS** [comment]
There is main request with all ready and merged improves.
Note me if you want some comments about code.

**Comment by ShikemokuMK** [comment]
I have merged this branch and checked sample game.
but it's not run correctly.
it's stopped in first [bg] tag.

**Comment by ValeryVS** [comment]
I forgot to update index.html file in repo and include
"animate.css"
and my
"animate.extend.css"
to it.

This is fixed now.

**Comment by ShikemokuMK** [comment]
I have merged this branch to "beta" branch.

I'll merge this branch to "master" and 
apply next major update. TyranoBuilder too .

thank you very much !

**Pull request closed without merging**
