### PR TITLE
Repo improve

### PR DESCRIPTION
**Pull request by ValeryVS**
Make うまく動作しない場合.txt readable for all language locales.
And add windows Thumbs.db to .gitignore file.
I think Mac's .DS_Store also can be ignored.

### CODE REVIEW

**Comment by geduld** [comment]
:+1:

**Comment by EvanBurchard** [comment]
:+1:

**Comment by geduld** [comment]
TIPS: Thumbs.dbファイルを作成しないようにする
http://www.atmarkit.co.jp/ait/articles/0602/04/news012.html

**Comment by geduld** [comment]
@ValeryVS Let me know if you need an assistant to communicate with @ShikemokuMK in Japanese. I can help you :)

**Comment by ValeryVS** [comment]
Thank you. I'm from Russia. Speak russian, english and learn japanese now. Perhapse some help with communication will be good.

First of all, I have some generic questions about developing and some features that KAG synthax doesn't have. Is it comfortable to talk on github or, may be, by email?

**Comment by geduld** [comment]
I think [Gitter](https://gitter.im/) is a reasonable option. I made [a public room](https://gitter.im/geduld/tyranoscript?utm_source=share-link&utm_medium=link&utm_campaign=share-link) for us. However, using a room bound to this repository is more better. I will make an offer to @ShikemokuMK to create new Gitter room.

**Comment by ShikemokuMK** [comment]
thanks.
I haven't noticed your pull request. sorry.

I'm going to confirm requests now.

**Pull request merged**
